### ISSUE TITLE
Erratic Behavior After Trying To Edit Preferences

### ISSUE THREAD

**Issue by jpmgoncalves** [coinbase/barbar#1]
Downloaded the app, ran it and I edited the preferences to be able to see ETH/USD as a primary and LTC/USD as secondary and then this is what happened: 

[Erratic Behavior After Trying To Edit Preferences.zip](https://github.com/coinbase/barbar/files/976965/Erratic.Behavior.After.Trying.To.Edit.Preferences.zip)

- Unable to see the info on the top bar;
- Unable to edit the preferences;
- Sometimes I'm able to see the dropdowns populated but if I click on them, the app stops.

**Comment by dai-cb** [comment]
@jpmgoncalves What version of MacOS are you running?

**Comment by jpmgoncalves** [comment]
@dai-cb, using Sierra, 10.12.4 (16E195).

**Comment by robertrichard** [comment]
I'm experiencing the same erratic behavior noted by @jpmgoncalves I have isolated the issue to whenever LTC is one of the currency pairs.  I'm currently running macOS Sierra 10.12.6 Beta (16G12b).

**Comment by dstuecken** [comment]
I've fixed the unexpected crash.

Check https://github.com/coinbase/barbar/pull/7

**Comment by maliknur** [comment]
same issue.. can someone generate build and upload it?

**Comment by euskadi31** [comment]
same issue

**Comment by dai-cb** [comment]
This is fixed now in master
