### ISSUE TITLE
Add third option?

### ISSUE THREAD

**Issue by RustyDev** [coinbase/barbar#2]
I'd love to be able to display BTC, ETH, and LTC. Thanks!

**Comment by dai-cb** [comment]
@RustyDev Yep, planning on it. Watch this space...

**Comment by stefanmendoza** [comment]
@dai-cb is the plan still to add this functionality? Is there a planned timeline?

**Comment by dai-cb** [comment]
Will look at extending it to add as many as you want rather than 1, 2 or 3
