### ISSUE TITLE
Dark Menubar is not supported

### ISSUE THREAD

**Issue by dstuecken** [coinbase/barbar#5]
If you have a dark menubar and use colored texts the price colors are black which results in an unreadable price.

**Comment by dstuecken** [comment]
Before:
<img width="161" alt="screenshot 2017-10-25 um 12 55 57" src="https://user-images.githubusercontent.com/493399/31995236-dd76c38a-b983-11e7-8236-c254eb65b00d.png">
<img width="174" alt="screenshot 2017-10-25 um 12 55 52" src="https://user-images.githubusercontent.com/493399/31995237-dd91a538-b983-11e7-841a-61275b7e049b.png">

After:
<img width="181" alt="screenshot 2017-10-25 um 12 52 46" src="https://user-images.githubusercontent.com/493399/31995210-c8d43b88-b983-11e7-87cc-e1c322d83e75.png">

**Comment by dai-cb** [comment]
This is fixed in master
